/**
 * Integration tests for xsec#569 — primitive synthesis + reproducer
 * minimization wired into the kernel-verify loop and finding promotion.
 */
import { describe, expect, it } from "vitest";
import {
  applyVerificationToFinding,
  verifyStaticKernelFinding,
  type KernelVerifyAgentInvoker,
  type KernelVerifyResult,
} from "./kernel-verify.js";
import { classifyKernelPrimitive } from "../triage/kernel-primitive.js";
import type { KernelVerifyRunner } from "./kernel-verify-types.js";
import type { Finding, CrashReport } from "@xsec/shared";
import type { NativeContentBlock } from "../runtime/types.js";

function staticKernelFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    id: "00000000-finding-0569",
    templateId: "kernel-review-test",
    title: "tcp_sendmsg: use-after-free on closed socket",
    description: "static-only kernel-review hypothesis",
    severity: "medium",
    category: "use-after-free",
    status: "discovered",
    evidence: {
      request: "net/ipv4/tcp.c:1234",
      response: "static-only",
      analysis: "Found by review agent\nSubsystem: net/tcp\nHypothesis: true",
    },
    confidence: 0.4,
    timestamp: 0,
    ...overrides,
  };
}

const UAF_REPRO = [
  "# autogenerated syzkaller repro",
  "r0 = socket$inet(0x2, 0x1, 0x0)",
  "setsockopt(r0, 0x1, 0x2, 0x0, 0x0)",
  "getsockname(r0, 0x0, 0x0)",
  "close(r0)",
  "sendto(r0, 0x0, 0x0, 0x0, 0x0, 0x0)",
].join("\n");

/** The crash needs socket creation AND the use-after-close send. */
function uafRunner(): KernelVerifyRunner {
  return async (input) => {
    const crashes =
      input.program.includes("socket$inet") && input.program.includes("sendto");
    return {
      ran: true,
      crashed: crashes,
      signatureMatched: crashes,
      detectedCrashType: crashes ? "kasan-uaf" : undefined,
      dmesgExcerpt: crashes
        ? "BUG: KASAN: slab-use-after-free in tcp_sendmsg+0x10/0x20\n" +
          "Write of size 8 at addr ffff8880aabbccdd by task poc/123\n" +
          "Allocated by task 122:\nFreed by task 123:"
        : "",
      reason: crashes ? "matched" : "no crash",
      oracleConfidence: crashes ? 0.95 : 0,
    };
  };
}

function confirmInvoker(): KernelVerifyAgentInvoker {
  let sent = false;
  return async () => {
    if (sent) throw new Error("invoker called more than once");
    sent = true;
    const block: NativeContentBlock = {
      type: "tool_use",
      id: "call-1",
      name: "kernel_run",
      input: { program: UAF_REPRO, program_lang: "syz" },
    };
    return [block];
  };
}

describe("verifyStaticKernelFinding (#569 minimization + primitive)", () => {
  it("confirms, classifies the write-UAF primitive, and minimizes the reproducer", async () => {
    const result = await verifyStaticKernelFinding(staticKernelFinding(), {
      kernelTree: "/tmp/linux",
      runner: uafRunner(),
      agentInvoker: confirmInvoker(),
      sourceSlice: [],
      minimize: true,
    });

    expect(result.status).toBe("confirmed");

    // Primitive synthesis from the confirmed dmesg.
    expect(result.primitive?.kind).toBe("use-after-free");
    expect(result.primitive?.control).toBe("write");
    expect(result.primitive?.controlDemo.kind).toBe("object-overwrite");

    // Minimization shrank the syscall list but kept the two essentials.
    expect(result.minimization).toBeDefined();
    expect(result.minimization!.reproduced).toBe(true);
    expect(result.minimization!.minimizedUnitCount).toBeLessThan(
      result.minimization!.originalUnitCount,
    );
    expect(result.minimized_program).toContain("socket$inet");
    expect(result.minimized_program).toContain("sendto");
    expect(result.minimized_program).not.toContain("getsockname");
    // generated_program is replaced with the minimized source.
    expect(result.generated_program).toBe(result.minimized_program);
  });

  it("does not minimize when opts.minimize is unset (default)", async () => {
    const result = await verifyStaticKernelFinding(staticKernelFinding(), {
      kernelTree: "/tmp/linux",
      runner: uafRunner(),
      agentInvoker: confirmInvoker(),
      sourceSlice: [],
    });
    expect(result.status).toBe("confirmed");
    expect(result.minimization).toBeUndefined();
    // Primitive is still synthesised even without minimization.
    expect(result.primitive?.kind).toBe("use-after-free");
    expect(result.generated_program).toBe(UAF_REPRO);
  });
});

describe("applyVerificationToFinding (#569 severity reflects exploitability)", () => {
  function writeUafReport(): CrashReport {
    return {
      rawText: "",
      crashType: "kasan-uaf",
      faultingFunction: "tcp_sendmsg",
      callStack: [],
      subsystem: "net/tcp",
      accessType: "write",
      accessSize: 8,
      allocSite: "alloc",
      freeSite: "free",
    };
  }

  it("escalates a medium finding to critical for a confirmed write-UAF primitive", () => {
    const primitive = classifyKernelPrimitive(writeUafReport());
    const result: KernelVerifyResult = {
      status: "confirmed",
      new_confidence: 1.0,
      signature: "kasan-uaf",
      generated_program: "REPRO",
      generated_program_lang: "syz",
      primitive,
      attempts: [],
    };
    const promoted = applyVerificationToFinding(
      staticKernelFinding({ severity: "medium" }),
      result,
    );
    expect(promoted.severity).toBe("critical");
    expect(promoted.evidence.analysis).toMatch(/---primitive---/);
    expect(promoted.evidence.analysis).toMatch(/Primitive: use-after-free/);
  });

  it("records the minimization summary in the analysis when present", () => {
    const primitive = classifyKernelPrimitive(writeUafReport());
    const result: KernelVerifyResult = {
      status: "confirmed",
      new_confidence: 1.0,
      signature: "kasan-uaf",
      generated_program: "MIN",
      generated_program_lang: "syz",
      minimized_program: "MIN",
      minimization: {
        program: "MIN",
        lang: "syz",
        originalUnitCount: 6,
        minimizedUnitCount: 2,
        removedUnits: ["a", "b", "c", "d"],
        oracleCalls: 9,
        reproduced: true,
        signature: "kasan-uaf",
        oneMinimal: true,
      },
      primitive,
      attempts: [],
    };
    const promoted = applyVerificationToFinding(staticKernelFinding(), result);
    expect(promoted.evidence.analysis).toMatch(/Reproducer minimized: 6 → 2 units/);
    expect(promoted.evidence.analysis).toMatch(/1-minimal/);
  });
});
