/**
 * Tests for the verify → weaponization splice (kernel-autonomy Phase 2a).
 *
 * Confirms the gate: `weaponize:false` leaves a confirmed finding byte-for-byte
 * unchanged from the pre-Phase-2a path; `weaponize:true` (with a stub harness)
 * populates `finding.kernelExploit.highestRung` and a `---weaponization---`
 * evidence block.
 */
import { describe, expect, it } from "vitest";
import {
  applyVerificationToFinding,
  verifyStaticKernelFinding,
  type KernelVerifyAgentInvoker,
} from "./kernel-verify.js";
import type { KernelVerifyRunner } from "./kernel-verify-types.js";
import type { Finding } from "@xsec/shared";
import type { NativeContentBlock } from "../runtime/types.js";
import type { ReproducerResult, CrashReport } from "../triage/kernel-oracle.js";

function staticKernelFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    id: "00000000-finding-wpn",
    templateId: "kernel-review-test",
    title: "tcp_sendmsg: use-after-free on closed socket",
    description: "static-only kernel-review hypothesis",
    severity: "medium",
    category: "use-after-free",
    status: "discovered",
    evidence: {
      request: "net/ipv4/tcp.c:1234",
      response: "static-only",
      analysis: "Found by review agent\nSubsystem: net/tcp\nHypothesis: true",
    },
    confidence: 0.4,
    timestamp: 0,
    ...overrides,
  };
}

const UAF_REPRO = [
  "# autogenerated syzkaller repro",
  "r0 = socket$inet(0x2, 0x1, 0x0)",
  "close(r0)",
  "sendto(r0, 0x0, 0x0, 0x0, 0x0, 0x0)",
].join("\n");

function uafRunner(): KernelVerifyRunner {
  return async (input) => {
    const crashes =
      input.program.includes("socket$inet") && input.program.includes("sendto");
    return {
      ran: true,
      crashed: crashes,
      signatureMatched: crashes,
      detectedCrashType: crashes ? "kasan-uaf" : undefined,
      dmesgExcerpt: crashes
        ? "BUG: KASAN: slab-use-after-free in tcp_sendmsg+0x10/0x20\n" +
          "Write of size 8 at addr ffff8880aabbccdd by task poc/123\n" +
          "Allocated by task 122:\nFreed by task 123:"
        : "",
      reason: crashes ? "matched" : "no crash",
      oracleConfidence: crashes ? 0.95 : 0,
    };
  };
}

function confirmInvoker(): KernelVerifyAgentInvoker {
  let sent = false;
  return async () => {
    if (sent) throw new Error("invoker called more than once");
    sent = true;
    const block: NativeContentBlock = {
      type: "tool_use",
      id: "call-1",
      name: "kernel_run",
      input: { program: UAF_REPRO, program_lang: "syz" },
    };
    return [block];
  };
}

/** Stub weaponization VM runner: scaffold compiles+runs, ATTEMPTED marker only. */
function attemptedOnlyVmRunner() {
  return async (report: CrashReport): Promise<ReproducerResult> => {
    const m = (report.reproducer ?? "").match(/#define OSEC_CANARY "([^"]+)"/);
    const canary = m?.[1] ?? "";
    return {
      compiled: true,
      executed: true,
      output: canary ? `xsec-CANARY:${canary}:ATTEMPTED:entry` : "ran",
      dmesg: "",
      exitCode: 0,
      timedOut: false,
    };
  };
}

describe("verify → weaponization splice (Phase 2a)", () => {
  it("weaponize:false leaves the confirmed finding unchanged", async () => {
    const result = await verifyStaticKernelFinding(staticKernelFinding(), {
      kernelTree: "/tmp/linux",
      runner: uafRunner(),
      agentInvoker: confirmInvoker(),
      sourceSlice: [],
      // weaponize omitted → default false
    });

    expect(result.status).toBe("confirmed");
    expect(result.weaponization).toBeUndefined();
    expect(result.kernelExploit).toBeUndefined();

    const finding = applyVerificationToFinding(staticKernelFinding(), result);
    expect(finding.kernelExploit).toBeUndefined();
    expect(finding.evidence.analysis).not.toContain("---weaponization---");
  });

  it("weaponize:true populates kernelExploit.highestRung + evidence block", async () => {
    const result = await verifyStaticKernelFinding(staticKernelFinding(), {
      kernelTree: "/tmp/linux",
      runner: uafRunner(),
      agentInvoker: confirmInvoker(),
      sourceSlice: [],
      weaponize: true,
      weaponizeArtifactsReady: () => true,
      weaponizeVmRunner: attemptedOnlyVmRunner(),
    });

    expect(result.status).toBe("confirmed");
    expect(result.weaponization).toBeDefined();
    // Honest: the stub scaffold only reaches the attempted rung.
    expect(result.weaponization!.highestRung).toBe("attempted");
    expect(result.kernelExploit?.highestRung).toBe("attempted");
    expect(result.kernelExploit?.lpeAchieved).toBe(false);

    const finding = applyVerificationToFinding(staticKernelFinding(), result);
    expect(finding.kernelExploit?.highestRung).toBe("attempted");
    expect(finding.evidence.analysis).toContain("---weaponization---");
    expect(finding.evidence.analysis).toContain("Highest rung: attempted");
    // The planner's missing-capability rationale rides into the evidence block.
    expect(finding.evidence.analysis).toMatch(/missing|Partial|kaslr-leak/);
  });

  it("weaponize:true with no QEMU artifacts runs plan-only (no crash, static rung)", async () => {
    const result = await verifyStaticKernelFinding(staticKernelFinding(), {
      kernelTree: "/tmp/linux",
      runner: uafRunner(),
      agentInvoker: confirmInvoker(),
      sourceSlice: [],
      weaponize: true,
      weaponizeArtifactsReady: () => false, // plan-only
    });

    expect(result.status).toBe("confirmed");
    expect(result.weaponization).toBeDefined();
    expect(result.weaponization!.highestRung).toBe("attempted");
    expect(result.kernelExploit?.lpeAchieved).toBe(false);
  });
});
