import { describe, expect, it } from "vitest";
import {
  minimizeReproducer,
  splitProgram,
  ddmin,
  makeKernelMinimizeOracle,
  type MinimizeOracle,
} from "./reproducer-minimize.js";
import type { KernelVerifyRunner } from "./kernel-verify-types.js";
import type { Finding } from "@xsec/shared";

// ── splitProgram ────────────────────────────────────────────────────────────

describe("splitProgram", () => {
  it("treats each non-comment syz line as a unit and drops comments on render", () => {
    const prog = ["# a syzkaller program", "r0 = socket(...)", "close(r0)"].join("\n");
    const { units, render } = splitProgram(prog, "syz");
    expect(units).toEqual(["r0 = socket(...)", "close(r0)"]);
    expect(render([0, 1])).toBe("r0 = socket(...)\nclose(r0)");
    expect(render([1])).toBe("close(r0)");
  });

  it("pins C structural lines so a minimized C program still compiles", () => {
    const prog = [
      "#include <stdio.h>",
      "int main(void) {",
      "  int fd = open(path);",
      "  ioctl(fd, EVIL);",
      "  return 0;",
      "}",
    ].join("\n");
    const { units, render } = splitProgram(prog, "c");
    expect(units).toEqual(["  int fd = open(path);", "  ioctl(fd, EVIL);"]);
    // Removing the ioctl unit keeps includes, main, return and braces.
    const rendered = render([0]);
    expect(rendered).toContain("#include <stdio.h>");
    expect(rendered).toContain("int main(void) {");
    expect(rendered).toContain("  int fd = open(path);");
    expect(rendered).not.toContain("ioctl(fd, EVIL);");
    expect(rendered).toContain("return 0;");
    expect(rendered.trimEnd().endsWith("}")).toBe(true);
  });
});

// ── ddmin core ──────────────────────────────────────────────────────────────

describe("ddmin", () => {
  it("reduces to the 1-minimal essential set", async () => {
    // Crashes iff BOTH index 1 and index 4 are present.
    const essential = new Set([1, 4]);
    const keep = await ddmin(6, async (idx) => {
      const s = new Set(idx);
      return [...essential].every((e) => s.has(e));
    });
    expect([...keep].sort((a, b) => a - b)).toEqual([1, 4]);
  });
});

// ── minimizeReproducer ───────────────────────────────────────────────────────

describe("minimizeReproducer", () => {
  // Acceptance scenario (#569): a multi-syscall UAF reproducer is minimized to
  // the two essential syscalls while still crashing.
  const UAF_REPRO = [
    "# autogenerated syzkaller repro",
    "r0 = socket$inet(0x2, 0x1, 0x0)",
    "setsockopt(r0, 0x1, 0x2, 0x0, 0x0)",
    "getsockname(r0, 0x0, 0x0)",
    "r1 = dup(r0)",
    "close(r0)",
    "sendto(r1, 0x0, 0x0, 0x0, 0x0, 0x0)",
  ].join("\n");

  // The crash needs the socket creation AND the use-after-close send.
  const ESSENTIAL = ["socket$inet", "sendto"];

  const uafOracle: MinimizeOracle = async (program) => {
    const crashes = ESSENTIAL.every((s) => program.includes(s));
    return { stillCrashes: crashes, signature: crashes ? "kasan-uaf" : undefined };
  };

  it("minimizes a UAF reproducer to fewer syscalls while still crashing", async () => {
    const result = await minimizeReproducer(UAF_REPRO, {
      lang: "syz",
      oracle: uafOracle,
    });
    expect(result.reproduced).toBe(true);
    // Started at 6 syscalls (comment dropped), shrank to the 2 essentials.
    expect(result.originalUnitCount).toBe(6);
    expect(result.minimizedUnitCount).toBeLessThan(result.originalUnitCount);
    expect(result.minimizedUnitCount).toBe(2);
    expect(result.program).toContain("socket$inet");
    expect(result.program).toContain("sendto");
    expect(result.program).not.toContain("getsockname");
    expect(result.signature).toBe("kasan-uaf");
    expect(result.oneMinimal).toBe(true);
    expect(result.removedUnits.length).toBe(4);
  });

  it("requires the expected signature to retain a candidate", async () => {
    const oracle: MinimizeOracle = async (program) => {
      // Everything 'crashes', but only the full program yields the UAF sig.
      const sig = program.includes("sendto") ? "kasan-uaf" : "kasan-oob";
      return { stillCrashes: true, signature: sig };
    };
    const result = await minimizeReproducer(UAF_REPRO, {
      lang: "syz",
      oracle,
      expectedSignature: "kasan-uaf",
    });
    expect(result.reproduced).toBe(true);
    expect(result.program).toContain("sendto");
    expect(result.signature).toBe("kasan-uaf");
  });

  it("returns the program unchanged when it does not reproduce", async () => {
    const neverCrashes: MinimizeOracle = async () => ({ stillCrashes: false });
    const result = await minimizeReproducer(UAF_REPRO, {
      lang: "syz",
      oracle: neverCrashes,
    });
    expect(result.reproduced).toBe(false);
    expect(result.minimizedUnitCount).toBe(result.originalUnitCount);
    expect(result.program).toBe(UAF_REPRO);
  });

  it("honours the oracle-call budget and reports non-1-minimal", async () => {
    let calls = 0;
    const oracle: MinimizeOracle = async (program) => {
      calls++;
      return {
        stillCrashes: ESSENTIAL.every((s) => program.includes(s)),
        signature: "kasan-uaf",
      };
    };
    const result = await minimizeReproducer(UAF_REPRO, {
      lang: "syz",
      oracle,
      maxOracleCalls: 2,
    });
    expect(result.oracleCalls).toBeLessThanOrEqual(2);
    expect(result.oneMinimal).toBe(false);
    expect(calls).toBeLessThanOrEqual(2);
  });
});

// ── makeKernelMinimizeOracle ─────────────────────────────────────────────────

describe("makeKernelMinimizeOracle", () => {
  function finding(): Finding {
    return {
      id: "f1",
      templateId: "kernel-review",
      title: "uaf",
      description: "",
      severity: "high",
      category: "use-after-free",
      status: "discovered",
      evidence: { request: "", response: "", analysis: "" },
      confidence: 0.4,
      timestamp: 0,
    };
  }

  it("maps a Tier-1 runner crash verdict to stillCrashes", async () => {
    const runner: KernelVerifyRunner = async (input) => ({
      ran: true,
      crashed: input.program.includes("sendto"),
      signatureMatched: false,
      detectedCrashType: input.program.includes("sendto") ? "kasan-uaf" : undefined,
      dmesgExcerpt: "",
      reason: "",
      oracleConfidence: 0.5,
    });
    const oracle = makeKernelMinimizeOracle({
      runner,
      finding: finding(),
      kernelTree: "/tmp/linux",
    });
    expect(await oracle("r0 = socket()\nsendto(r0)", "syz")).toEqual({
      stillCrashes: true,
      signature: "kasan-uaf",
    });
    expect(await oracle("r0 = socket()", "syz")).toEqual({
      stillCrashes: false,
      signature: undefined,
    });
  });
});
