/**
 * CVSS 4.0 base-score computation, vector parsing, and report rendering.
 *
 * The scoring engine is a faithful port of the FIRST.org CVSS v4.0 reference
 * implementation (the MacroVector method + published lookup table). The fixture
 * scores below were generated by running the *official* reference JS
 * (cvss_score.js + cvss_lookup.js) over each vector, so they assert our port
 * reproduces the reference algorithm exactly.
 *
 * 3.1 support (suggestCvss) is covered by cvss.impact.test.ts and is untouched.
 */

import { describe, it, expect } from "vitest";
import type { Finding, ImpactAssessment } from "@xsec/shared";
import {
  computeCvss4BaseScore,
  parseCvss4Vector,
  scoreCvss4Vector,
  cvss4Severity,
  formatCvss4Vector,
  suggestCvss4,
  renderCvssSection,
  Cvss4ParseError,
  suggestCvss,
} from "./cvss.js";

// vector → expected base score (ground truth from the official reference impl).
const FIXTURES: Array<[string, number]> = [
  ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H", 10.0],
  ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:N/VI:N/VA:N/SC:N/SI:N/SA:N", 0.0],
  ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N", 9.3],
  ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:P/VC:H/VI:H/VA:H/SC:L/SI:L/SA:L", 8.7],
  ["CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N", 8.5],
  ["CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:L/VI:N/VA:N/SC:N/SI:N/SA:N", 6.9],
  ["CVSS:4.0/AV:P/AC:H/AT:P/PR:H/UI:A/VC:L/VI:L/VA:L/SC:L/SI:L/SA:L", 1.0],
  ["CVSS:4.0/AV:A/AC:L/AT:N/PR:L/UI:P/VC:L/VI:L/VA:N/SC:H/SI:H/SA:H", 4.7],
  ["CVSS:4.0/AV:N/AC:H/AT:P/PR:N/UI:N/VC:H/VI:L/VA:L/SC:H/SI:L/SA:L", 9.1],
];

describe("CVSS 4.0 base-score — reference fixtures", () => {
  for (const [vector, expected] of FIXTURES) {
    it(`${vector} → ${expected}`, () => {
      expect(computeCvss4BaseScore(parseCvss4Vector(vector))).toBe(expected);
      expect(scoreCvss4Vector(vector).score).toBe(expected);
    });
  }

  it("rates severity per the CVSS 4.0 scale", () => {
    expect(cvss4Severity(0)).toBe("None");
    expect(cvss4Severity(3.9)).toBe("Low");
    expect(cvss4Severity(4.0)).toBe("Medium");
    expect(cvss4Severity(6.9)).toBe("Medium");
    expect(cvss4Severity(7.0)).toBe("High");
    expect(cvss4Severity(8.9)).toBe("High");
    expect(cvss4Severity(9.0)).toBe("Critical");
    expect(cvss4Severity(10)).toBe("Critical");
  });

  it("attaches the qualitative rating to scoreCvss4Vector", () => {
    const r = scoreCvss4Vector(FIXTURES[0][0]);
    expect(r.score).toBe(10.0);
    expect(r.severity).toBe("Critical");
    expect(r.macroVector).toMatch(/^\d{6}$/);
  });
});

describe("parseCvss4Vector — validation", () => {
  it("rejects a non-4.0 prefix", () => {
    expect(() => parseCvss4Vector("CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H")).toThrow(
      Cvss4ParseError,
    );
  });
  it("rejects an unknown metric", () => {
    expect(() =>
      parseCvss4Vector("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H/ZZ:Q"),
    ).toThrow(Cvss4ParseError);
  });
  it("rejects an illegal value", () => {
    expect(() =>
      parseCvss4Vector("CVSS:4.0/AV:Q/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H"),
    ).toThrow(Cvss4ParseError);
  });
  it("rejects a missing mandatory base metric (no SA)", () => {
    expect(() =>
      parseCvss4Vector("CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H"),
    ).toThrow(Cvss4ParseError);
  });
  it("rejects a duplicate metric", () => {
    expect(() =>
      parseCvss4Vector("CVSS:4.0/AV:N/AV:A/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:H/SI:H/SA:H"),
    ).toThrow(Cvss4ParseError);
  });
  it("accepts threat/environmental metrics and round-trips canonically", () => {
    const sel = parseCvss4Vector(
      "CVSS:4.0/AV:N/AC:L/AT:N/PR:N/UI:N/VC:H/VI:H/VA:H/SC:N/SI:N/SA:N/E:P/CR:H",
    );
    // X-valued and absent metrics are dropped from the canonical string.
    expect(formatCvss4Vector(sel)).toContain("/E:P");
    expect(formatCvss4Vector(sel)).toContain("/CR:H");
  });
});

function mkFinding(overrides: Partial<Finding> = {}): Finding {
  return {
    id: "F-1",
    templateId: "t-1",
    title: "Command injection in webhook handler",
    description: "User input flows into a shell without escaping.",
    severity: "critical",
    category: "command-injection",
    status: "verified",
    evidence: { request: "", response: "", analysis: "" },
    ...overrides,
  } as Finding;
}

const REMOTE: ImpactAssessment = {
  reachability_tier: "remote-unauth",
  blast_radius: "all tenants",
  weaponizability: "rce",
  business_impact: "headline",
  rationale: "reachable pre-auth",
};

describe("suggestCvss4 — finding → 4.0 vector", () => {
  it("produces a parseable, scorable 4.0 vector from a finding", () => {
    const s = suggestCvss4(mkFinding());
    const parsed = parseCvss4Vector(s.vector);
    expect(computeCvss4BaseScore(parsed)).toBe(s.score);
    expect(s.source).toBe("heuristic");
    expect(s.vector.startsWith("CVSS:4.0/")).toBe(true);
  });

  it("uses the reachability assessment for exploitability when present", () => {
    const s = suggestCvss4(mkFinding({ impactAssessment: REMOTE }));
    expect(s.source).toBe("impact-assessment");
    expect(s.vector).toContain("/AV:N/");
    expect(s.score).toBeGreaterThan(0);
  });

  it("does not perturb the 3.1 suggestion (both are independent)", () => {
    const f = mkFinding({ impactAssessment: REMOTE });
    const v31 = suggestCvss(f);
    expect(v31.vector.startsWith("CVSS:3.1/")).toBe(true);
    expect(v31.score).toBeGreaterThan(0);
  });
});

describe("renderCvssSection", () => {
  it("labels a 4.0 vector", () => {
    const line = renderCvssSection({ vector: FIXTURES[0][0], score: 10, severity: "Critical" });
    expect(line).toContain("CVSS 4.0");
    expect(line).toContain("10.0 (Critical)");
    expect(line).toContain(FIXTURES[0][0]);
  });
  it("labels a 3.1 vector", () => {
    const line = renderCvssSection({ vector: "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H", score: 9.8 });
    expect(line).toContain("CVSS 3.1");
    expect(line).toContain("9.8");
  });
});
